apiVersion: apps/v1
kind: Deployment
metadata:
  name: customersapi-deployment
  labels:
    app: customersapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customersapi
  template:
    metadata:
      labels:
        app: customersapi
    spec:
      containers:
        - name: customersapi
          image: vehicletracking.azurecr.io/customersapi:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"

      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: customersapi-service
spec:
  type: NodePort
  selector:
    app: customersapi
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 31000